### ISSUE TITLE
vertical recyclerview inside horizontal recyclerview

### ISSUE THREAD

**Issue by DarbinyanMher** [jeffreyliu8/Nested-RecyclerView#3]
Hi!
How can I change it and make vertical recycler view inside horizontal recyclerview?

**Comment by Joisar** [comment]
For inner recycler view, use layoutManager.setOrientation(LinearLayoutManager.VERTICAL) instead of  layoutManager.setOrientation(LinearLayoutManager.HORIZONTAL)
For outer recler view, use layoutManager.setOrientation(LinearLayoutManager.HORIZONTAL)

**Comment by jeffreyliu8** [comment]
Thanks for the answer.
