### ISSUE TITLE
RecycledViewPool

### ISSUE THREAD

**Issue by ThirdPrince** [jeffreyliu8/Nested-RecyclerView#4]
recycledviewpool can improve efficiency? is it necessary？

**Comment by jeffreyliu8** [comment]
It's not necessary, but it makes app more performant. https://proandroiddev.com/optimizing-nested-recyclerview-a9b7830a4ba7

**Comment by jeffreyliu8** [comment]
https://developer.android.com/topic/performance/vitals/render#recyclerview_nested_recyclerviews
